[package]
name = "parse_listen"
version = "0.1.0"
edition = "2024"

[dependencies]
gl = "0.14.0"
glfw = "0.59.0"
serde_json = "1.0"
serde = { version = "1.0.219", features = ["derive"] }
rand = "0.9.2"

[build-dependencies]
cc = "1.0"

